# Logistic Regression Using Mammography Data

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split 
from sklearn import metrics

# Instantiate Models/Estimators
regression = LogisticRegression()
accuracy = metrics.accuracy_score

/Users/kerrylam/anaconda/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:
data = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/mammographic-masses/mammographic_masses.data", header = None) #column name correct
data.columns = ["BI-RADS Assessment", "Age","Shape","Margin","Density","Severity"]
data.shape # Shape of DataFrame (observations, features)
# data.head()
print (data.shape)

(961, 6)

In [3]:
# Removing Data With Missing Values
data = data.replace("?", np.NaN)
data.dropna(inplace = True)

data.head()

   BI-RADS Assessment Age Shape Margin Density  Severity
0                   5  67     3      5       3         1
2                   5  58     4      5       3         1
3                   4  28     1      1       3         0
8                   5  57     1      5       3         1
10                  5  76     1      4       3         1

In [4]:
features = data.ix[:,1:6] # Counts last 5 features
x_data = features 
y_data = data["BI-RADS Assessment"] 
print (x_data.shape) 
print (y_data.shape)

(830, 5)
(830,)

In [5]:
x_train_data, x_test_data, y_train_data, y_test_data = \
train_test_split(x_data, y_data, test_size = 0.40)

In [6]:
a = ["Observations, Features for Training Set:"]
b = ["Response vector for Training Set:"]
c = ["Observations, Features for Testing Set:"]
d = ["Response vector for Testing Set:"]

print (a, x_train_data.shape)
print (b, y_train_data.shape)
print (c, x_test_data.shape)
print (d, y_test_data.shape)

['Observations, Features for Training Set:'] (498, 5)
['Response vector for Training Set:'] (498,)
['Observations, Features for Testing Set:'] (332, 5)
['Response vector for Testing Set:'] (332,)

In [7]:
regression.fit(x_data, y_data)
regression.predict(x_data)
response_prediction = regression.predict(x_data)
# len(response_prediction)

In [8]:
print(accuracy(y_data, response_prediction))

0.802409638554

In [9]:
# Testing Model With Random Measurements From The Dataset Below
out_of_sample_data = np.array([72,4,3,3,0])
measurements = out_of_sample_data.reshape(1,-1)
x = regression.predict(measurements)
print("BI-RADS Assessment:", x)

BI-RADS Assessment: ['4']

In [10]:
data.ix[142:240,:]

    BI-RADS Assessment Age Shape Margin Density  Severity
143                  4  47     1      1       2         0
145                  5  62     4      5       3         1
146                  5  63     4      4       3         1
148                  4  71     4      4       3         1
149                  4  41     1      1       3         0
150                  5  57     4      4       4         1
151                  5  71     4      4       4         1
152                  4  66     1      1       3         0
153                  4  47     2      4       2         0
154                  3  34     4      4       3         0
155                  4  59     3      4       3         0
160                  5  67     4      4       3         1
161                  4  41     2      1       3         0
162                  4  23     3      1       3         0
164                  4  42     2      1       3         0
165                  5  87     4      5       3         1
166                  4  68     1      1       3         1
167                  4  64     1      1       3         0
168                  5  54     3      5       3         1
169                  5  86     4      5       3         1
170                  4  21     2      1       3         0
172                  4  53     4      4       3         0
173                  4  44     4      4       3         0
174                  4  54     1      1       3         0
175                  5  63     4      5       3         1
177                  4  45     2      1       2         0
178                  5  71     4      5       3         0
179                  5  49     4      4       3         1
180                  4  49     4      4       3         0
181                  5  66     4      4       4         0
..                 ...  ..   ...    ...     ...       ...
205                  5  72     4      5       3         1
206                  4  46     2      3       3         0
207                  4  43     4      3       3         1
210                  4  46     1      1       1         0
211                  4  69     3      1       3         0
213                  5  43     2      1       3         1
214                  5  76     4      5       3         1
215                  4  46     1      1       3         0
216                  4  59     2      4       3         0
217                  4  57     1      1       3         0
219                  3  45     2      1       3         0
220                  3  43     2      1       3         0
221                  4  45     2      1       3         0
222                  5  57     4      5       3         1
223                  5  79     4      4       3         1
224                  5  54     2      1       3         1
225                  4  40     3      4       3         0
226                  5  63     4      4       3         1
228                  4  52     2      1       3         0
229                  4  38     1      1       3         0
230                  3  72     4      3       3         0
231                  5  80     4      3       3         1
232                  5  76     4      3       3         1
233                  4  62     3      1       3         0
234                  5  64     4      5       3         1
235                  5  42     4      5       3         0
237                  4  64     4      5       3         0
238                  4  63     4      4       3         1
239                  4  24     2      1       2         0
240                  5  72     4      4       3         1

[81 rows x 6 columns]